name: Build and Upload Releases
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.13.1
      - name: Pre-build project
        run: |
          go run tools/prebuildstep.go
      - name: Build project
        run: |
          GOOS=darwin GOARCH=amd64 go build -o gocaves-macos
          GOOS=linux GOARCH=amd64 go build -o gocaves-linux
          GOOS=windows GOARCH=amd64 go build -o gocaves-windows.exe
      - name: Generate name
        id: relname
        run: |
          echo "::set-output name=version::$(ruby -e 'puts `git describe --tags`.sub(/(-(\d+).*)?$/) {|x| "-#{$2.to_i + 1}"}')"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          tag_name: "${{ steps.relname.outputs.version }}"
          release_name: "Release ${{ steps.relname.outputs.version }} "
          draft: false
          prerelease: true
      - name: Upload Linux Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          upload_url: "${{ steps.create_release.outputs.upload_url }}"
          asset_path: ./gocaves-linux
          asset_name: gocaves-linux
          asset_content_type: application/octet-stream
      - name: Upload OSX Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          upload_url: "${{ steps.create_release.outputs.upload_url }}"
          asset_path: ./gocaves-macos
          asset_name: gocaves-macos
          asset_content_type: application/octet-stream
      - name: Upload Windows Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          upload_url: "${{ steps.create_release.outputs.upload_url }}"
          asset_path: ./gocaves-windows.exe
          asset_name: gocaves-windows.exe
          asset_content_type: application/octet-stream
