name: Build and Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.13.1
      - name: Pre-build project
        run: |
          go run tools/prebuildstep.go
      - name: Test project
        run: |
          go test ./...
