name: Run Linter
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.13.1
      - name: Pre-build project
        run: |
          go run tools/prebuildstep.go
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
